Whitespace fixes in IPv6 ping output
iputils/iputils pull request #478
Opened 2023-06-23 04:17 UTC by nmeyerhans

This change makes a couple small tweaks to the IPv6 ping output to make it more consistent with the IPv4 output and less confusing.

Closes #455 

Comparison of output before and after this change when pinging a host with reverse DNS (note the "PING" line):

Before:
```plain
$ ./builddir/ping/ping -6 -c1 minas.morgul.net
PING minas.morgul.net(minas.morgul.net (2603:400a:ffff:bb8::801f:30)) 56 data bytes
64 bytes from minas.morgul.net (2603:400a:ffff:bb8::801f:30): icmp_seq=1 ttl=40 time=80.9 ms

--- minas.morgul.net ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 80.885/80.885/80.885/0.000 ms
```

After:
```plain
$ ./builddir/ping/ping -6 -c1 minas.morgul.net
PING minas.morgul.net (2603:400a:ffff:bb8::801f:30) 56 data bytes
64 bytes from minas.morgul.net (2603:400a:ffff:bb8::801f:30): icmp_seq=1 ttl=40 time=81.5 ms

--- minas.morgul.net ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 81.508/81.508/81.508/0.000 ms
```

A host without reverse DNS:

Before:
```plain
$ ./builddir/ping/ping -6 -c1 s3.dualstack.us-west-2.amazonaws.com
PING s3.dualstack.us-west-2.amazonaws.com(2600:1fa0:402c:1140:34da:dd70:: (2600:1fa0:402c:1140:34da:dd70::)) 56 data bytes
64 bytes from 2600:1fa0:402c:1140:34da:dd70:: (2600:1fa0:402c:1140:34da:dd70::): icmp_seq=1 ttl=225 time=15.0 ms

--- s3.dualstack.us-west-2.amazonaws.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 14.972/14.972/14.972/0.000 ms
```
After:
```plain
$ ./builddir/ping/ping -6 -c1 s3.dualstack.us-west-2.amazonaws.com
PING s3.dualstack.us-west-2.amazonaws.com (2600:1fa0:40c9:1a81:34da:a9d8::) 56 data bytes
64 bytes from 2600:1fa0:40c9:1a81:34da:a9d8::: icmp_seq=1 ttl=221 time=16.0 ms

--- s3.dualstack.us-west-2.amazonaws.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 15.962/15.962/15.962/0.000 ms
```

When pinging a host with name resolution disabled (with the `-n` flag), output is similar to that of a host without reverse DNS, so it changes from:

```
$ ./builddir/ping/ping -6 -c1 minas.morgul.net -n
PING minas.morgul.net(2603:400a:ffff:bb8::801f:30) 56 data bytes
64 bytes from 2603:400a:ffff:bb8::801f:30: icmp_seq=1 ttl=40 time=81.2 ms

--- minas.morgul.net ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 81.205/81.205/81.205/0.000 ms
```

to 

```
$ ./builddir/ping/ping -6 -c1 minas.morgul.net -n
PING minas.morgul.net (2603:400a:ffff:bb8::801f:30) 56 data bytes
64 bytes from 2603:400a:ffff:bb8::801f:30: icmp_seq=1 ttl=40 time=81.0 ms

--- minas.morgul.net ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 80.950/80.950/80.950/0.000 ms
```

2023-07-08 12:56 UTC, nmeyerhans commented
@pevik Any feedback on this?

2023-07-09 09:29 UTC, pevik commented
@nmeyerhans I'm sorry, I completely forgot on this. Generally LGTM, I'll have look and merge during next week.

2023-07-10 17:06 UTC, pevik commented
Second (probably) commit breaks IPv4. It adds extra space:
```
$ ./ping/ping -c1 s3.dualstack.us-west-2.amazonaws.com -4
PING  (52.92.240.224) 56(84) bytes of data.
64 bytes from s3-us-west-2.amazonaws.com (52.92.240.224): icmp_seq=1 ttl=230 time=175 ms
```
With a simple debug: https://github.com/pevik/iputils/commit/9274d2254f690e6054dd220443ac5c6a03f5ffe0 (added quotes) it's obvious:
```
$ ./ping/ping -c1 s3.dualstack.us-west-2.amazonaws.com -4
PING '' (52.92.241.216) 56(84) bytes of data.
64 bytes from s3-us-west-2.amazonaws.com (52.92.241.216): icmp_seq=1 ttl=229 time=174 ms
```
Could you please fix that.

2023-08-10 06:59 UTC, pevik requested changes
Second (probably) commit breaks IPv4. It adds extra space (see my previous comment).

2023-08-12 22:04 UTC, robert-scheck commented
But isn't the real issue here not the extra whitespace but that "nothing" is printed by `%s` instead of printing "s3.dualstack.us-west-2.amazonaws.com"? This at least what I would expect.

2023-08-17 04:32 UTC, pevik commented
> But isn't the real issue here not the extra whitespace but that "nothing" is printed by `%s` instead of printing "s3.dualstack.us-west-2.amazonaws.com"? This at least what I would expect.

Yes, you're right. It looks like it's setup specific (I previously thought it's reproducible everywhere, I often test on system with disabled IPv6, which does not have this problem) and on affected system the problem is also on current master. I suppose we can merge this, because problem I found is a separate issue.

2023-08-17 16:25 UTC, closed without merging